meta-qt5/meta-qt5

recipes-qt/qt5/qtscript/0001-javascriptcore-Use-64-bit-ints.patch
recipes-qt/qt5/qtscript_git.bb

Fix errors like this:
error: cast from 'QTJSC::JSCell*' to 'int32_t' {aka 'int'} loses precision
when cross compiling for RISC-V.
Signed-off-by: Alistair Francis <alistair.francis@wdc.com>

qt5/qtscript: Fix qtscript cross compile error

---

recipes-qt/qt5/qtbase_git.bb

qtbase configure option -ltcg enables Link Time Code Generation
using GCC's LTO feature. Enable it by default if the selected
optimization is for size.

qtbase: add PACKAGECONFIG for Link Time Optimization

---

recipes-qt/qt5/qttools_git.bb

If host has clang installed, the qdoc is enabled doing host
contamination. For now, we disable this completely.
Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>

qttools: Disable clang support

---

recipes-qt/qt5/qttranslations_git.bb

The qt_xx packages are meta catalogs that have dependencies to
qtquick1 which is not available anymore, which then breaks loading
of the translation file.

qttranslations: do not use qt meta catalog translation package

---

recipes-qt/qt5/nativesdk-qtbase_git.bb
recipes-qt/qt5/qtbase_git.bb

When running the task "do_populate_sdk()" for an image inheriting from
"populate_sdk_qt5.bbclass", the following error could be observed in
case PACKAGE_CLASSES included "package_rpm":
ERROR: Could not invoke dnf.
[...]
Error:
Problem: package packagegroup-qt5-toolchain-target-1.0-r0.noarch
requires qtbase-mkspecs, but none of the providers can be
installed
- conflicting requests
- nothing provides /usr/bin/python needed by
qtbase-mkspecs-5.10.1+git0+6c6ace9d23-r0.armv5e
The script file in question that requires python to run is located at
"/usr/lib/qt5/mkspecs/features/uikit/devices.py".
Signed-off-by: Dennis Menschel <menschel-d@posteo.de>
---
The changes have been tested with `MACHINE = "qemuarm"` and an extended `core-image-minimal` that inherits from `populate_sdk_qt5.bbclass`.

[sumo] qtbase-mkspecs: fix runtime dependency on python

---

recipes-qt/qt5/qt5.inc
recipes-qt/qt5/qtbase/0001-Add-linux-oe-g-platform.patch
recipes-qt/qt5/qtbase_git.bb
recipes-qt/qt5/qtdeclarative_git.bb
recipes-qt/qt5/qtwebengine_git.bb

Add PACKAGECONFIG that enables static build for qtbase and consequently
to all Qt recipes. This can be enabled with DISTRO_FEATURE 'qt5-static',
which also adds qtdeclarative-native dependency to all recipes that
depend on qtdeclarative as it's required for qmlimportscannertool.
Building examples and tests with static build can take excessive amounts
of time and disk space, so disabling DISTRO_FEATURE 'ptest' and
PACKAGECONFIGs 'examples' from qtbase is advised.
Not all recipes support static builds and those are not fixed here.

qt5: add option to build Qt5 statically

---

recipes-qt/qt5/qtbase_git.bb

If trying to build KDE there are extra package config options required.
This patch adds a KDE DISTRO_CONFIG that enables the extra
PACKAGE_CONFIG options required.
Signed-off-by: Alistair Francis <alistair.francis@wdc.com>

qtbase: Add a kde DISTRO_CONFIG

---

recipes-qt/qt5/qtbase/0003-qlibraryinfo-allow-to-set-qt.conf-from-the-outside-u.patch

The same warning is present on the sumo branch, let us silent it :-)
The environment variable is empty when running qmake from SDK or
in device, which gives 'Empty filename passed to function' warning.
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
(cherry picked from commit 65db89eb7b6a9b53f7877d6e16bc4deeb367c285)

qtbase: don't pass empty filename to function

---

recipes-qt/packagegroups/nativesdk-packagegroup-qt5-toolchain-host.bb

perl modules are needed for syncqt.pl

nativesdk-packagegroup-qt5-toolchain-host: Add perl modules

---

recipes-qt/qt5/qt3d-runtime_git.bb

The Qt 3D Studio Runtime provides C++ and QML APIs for integrating
Qt 3D Studio scenes into Qt applications, as well as the viewer
application that is used in combination with the Qt 3D Studio
application during the design phase

add recipe for Qt 3D Studio runtime libraries

---

recipes-qt/qt5/qtbase_git.bb

These features depend on underlying syscall support in kernel
and if older kernels are in use, then we can have a knob to
turn them off.
Signed-off-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Alban Bedel <alban.bedel@avionic-design.de>
(cherry picked from commit 1ac92b6d8a7e1e1395929c87465e347789961086)

qtbase: Add packageconfigs for renameat2 and getentropy use

---

recipes-qt/qt5/qtwebkit_git.bb

Fix the following error during do_configure
| CMake Error at
|   Could NOT find BISON (missing: BISON_EXECUTABLE) (Required is at
least
|   version "2.1")
| Call Stack (most recent call first):
Add dependency to bison-native to fix the above error
Signed-off-by: Manjukumar Matha <manjukumar.harthikote-matha@xilinx.com>

qtwebkit_git.bb: Fix configure failure on bison

---

recipes-qt/packagegroups/packagegroup-qt5-toolchain-target.bb

Resolves #129
Signed-off-by: Scott Ellis <scott@jumpnowtek.com>

packagegroup-qt5-toolchain-target: Skip qtwebkit if opengl not found

---

recipes-python/pyqt5/python-pyqt5.inc

The fix to reset PARALLEL_MAKEINST doesn't work here because qmake
bbclass creates EXTRA_OEMAKE where it passes the -jX via MAKEFLAGS
its better to set MAKEFLAGS in do_install to undo that effect
Signed-off-by: Khem Raj <raj.khem@gmail.com>

python-pyqt5: MAKEFLAGS pass -j 1 via MAKEFLAGS during do_install

---

recipes-qt/qt5/qtwebengine_git.bb

Fixes #137
Apparently, this was fairly easy :)
The `NINJAFLAGS` environment variable is picked up by `src/core/gn_run.pro`

qtwebengine: Configure Ninja to honor PARALLEL_MAKE

---

recipes-qt/qt5/qtwayland_git.bb

The issue from 5.11 still exists in 5.12.
These header files were missing for me:
diff -rq 5.6.3-129-r0-do-install-*/image
Only in 5.6.3-129-r0-do-install-meta-qt5/image/usr/include/QtCompositor/5.6.3/QtCompositor/private: qwayland-server-hardware-integration.h
Only in 5.6.3-129-r0-do-install-meta-qt5/image/usr/include/QtCompositor/5.6.3/QtCompositor/private: qwayland-server-input-method.h
Only in 5.6.3-129-r0-do-install-meta-qt5/image/usr/include/QtCompositor/5.6.3/QtCompositor/private: qwayland-server-qtkey-extension.h
Only in 5.6.3-129-r0-do-install-meta-qt5/image/usr/include/QtCompositor/5.6.3/QtCompositor/private: qwayland-server-server-buffer-extension.h
Only in 5.6.3-129-r0-do-install-meta-qt5/image/usr/include/QtCompositor/5.6.3/QtCompositor/private: …

qtwayland: improve manual header installation

---

recipes-qt/qt5/qt3d_git.bb
recipes-qt/qt5/qtknx_git.bb
recipes-qt/qt5/qtmqtt_git.bb
recipes-qt/qt5/qtopcua_git.bb
recipes-qt/qt5/qtremoteobjects_git.bb
recipes-qt/qt5/qttools_git.bb

* v5.12.3 tags in qtknx, qtmqtt, qtopcua, qttools, qtremoteobjects are fine now, but qt3d still isn't in 5.12 branch
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>

qt5: partial fix for v5.12.3 tags

---

recipes-qt/qt5/qtwebengine/0001-Force-host-toolchain-configuration.patch
recipes-qt/qt5/qtwebengine/0002-musl-don-t-use-pvalloc-as-it-s-not-available-on-musl.patch
recipes-qt/qt5/qtwebengine/0003-musl-link-against-libexecinfo.patch
recipes-qt/qt5/qtwebengine_git.bb

* it was fixed in:
https://github.com/meta-qt5/meta-qt5/commit/5be2654885b3699520c4370579c929e2ce352e80
* but then when upgrading to 5.12.3 from meta-qt5/qtwebengine I've accidentally overwritten
this one with the older version in:
https://github.com/meta-qt5/meta-qt5/commit/e2707a016c3475c167a421c9c73d88f81cc61bd1
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>

qtwebengine: restore the fix for build with clang/libc++ on aarch64/arm

---

recipes-qt/qt5/nativesdk-qtbase_git.bb
recipes-qt/qt5/qtbase-native_git.bb
recipes-qt/qt5/qtbase/0017-Fix-Wdeprecated-copy-warnings.patch
recipes-qt/qt5/qtbase/0018-Always-build-uic-and-qvkgen.patch
recipes-qt/qt5/qtbase/0019-Avoid-renameeat2-for-native-sdk-builds.patch
recipes-qt/qt5/qtbase/0020-Bootstrap-without-linkat-feature.patch
recipes-qt/qt5/qtbase_git.bb

* some components which use Werror started to fail with gcc-9, because of new warning:
https://gcc.gnu.org/gcc-9/changes.html
New warnings:
-Wdeprecated-copy, implied by -Wextra, warns about the C++11
deprecation of implicitly declared copy constructor and
assignment operator if one of them is user-provided.
-Wdeprecated-copy-dtor also warns if the destructor is
user-provided, as specified in C++11.
* e.g. maliit-framework-qt5 was now failing with:
maliit-framework-qt5/0.99.0+gitAUTOINC+62bd54bcde-r0/recipe-sysroot/usr/include/QtCore/qvariant.h:273:25:
error: implicitly-declared 'constexpr QVariant::Private& QVariant::Private::operator=(const QVariant::Private&)' is deprecated [-Werror=deprecated-copy]
273 |     { other.d = Private(); }
|                         ^
Signed-off-by: Martin …

qtbase: fix build with gcc-9

---

conf/layer.conf

* there are couple things people need to provide to even parse
meta-qt5 dunfell branch with older than dunfell release of oe-core
so I don't want to mark it as compatible, people who understand how
to provide these missing bits will know how to override
LAYERSERIES_COMPAT_qt5-layer from their own layer (which needs to
be parsed before meta-qt5 layer - I suggest to use something like
separate meta-qt5-compat layer)
the required work arounds (these are the examples to build dunfell
branch from zeus:
1) mime-xdg.bbclass, e.g.:
https://github.com/webOS-ports/meta-webos-ports/commit/e57440cb97b210e86991dd0ff2ec53c50d6e0494
2) gstreamer1.0-plugins-good PACKAGECONFIG:
https://github.com/webOS-ports/meta-webos-ports/commit/75fd06799bf32eca6700bdf6066d509cf36f3049
3) meta-python2: …

layer: Mark dunfell as the only compatible release

---

recipes-qt/qt5/qtwebengine_git.bb

Its needed for xcb platform which means its not needed when x11 is not
in distro features, limit the scope of this dependency to x11
fixes non-x11 builds
Signed-off-by: Khem Raj <raj.khem@gmail.com>

qtwebengine: Add libxkbfile only when x11 is in distro features

---

recipes-qt/examples/cinematicexperience_1.0.bb

When running this demo under non-root user it often does not come up
because the asset are non-readable for non-root users e.g. weston user
when running weston based images.
Fixes
raspberrypi4-64:/usr/share/cinematicexperience-1.0$ ./Qt5_CinematicExperience
file:///usr/share/cinematicexperience-1.0/Qt5_CinematicExperience.qml:30:5: Type InfoView unavailable
InfoView {
^
file:///usr/share/cinematicexperience-1.0/content/InfoView.qml: Permission denied
^C
buildhistory view after the change
--- a/packages/cortexa72-yoe-linux-musl/cinematicexperience/sysroot
+++ b/packages/cortexa72-yoe-linux-musl/cinematicexperience/sysroot
@@ -5,11 +5,11 @@ drwxr-xr-x -          -                4096 ./usr/share
drwxr-xr-x -          -                4096 ./usr/share/cinematicexperience-1.0
drwxr-xr-x - …

cinematicexperience: Fix file permisions for non-root user

---

classes/qmake5_base.bbclass

Its a global setting
Signed-off-by: Khem Raj <raj.khem@gmail.com>

qmake5_base.bbclass: Remove remove-libtool from recipe scope

---

recipes-qt/qt5/qtbase/0026-QSslSocket-make-it-work-with-OpenSSL-v3.patch
recipes-qt/qt5/qtbase_git.bb

From lts 5.15.11-lts-lgpl and [1].
Resolves error:
```
QSslSocket: cannot call unresolved function SSL_get_peer_certificate
```
1: https://code.qt.io/cgit/qt/qtbase.git/commit/?h=v5.15.11-lts-lgpl&id=40c11752580802521d2fa10e4e036df61083ca42
See related discussion in https://github.com/meta-qt5/meta-qt5/pull/533

qtbase: Fix for OpenSSLV3

---

classes/qmake5.bbclass

A recent change in bitbake [1] has caused a build failure in qtwebkit. The fix with how the EXPORT_FUNCTIONS is being handled means that it is running into a collision with the explicit do_configure defined in this file.
This fix moves the explicit do_configure and do_insatll to use the EXPORT_FUNCTIONS methodology so that the conflict is resolved correctly.
[1] https://git.openembedded.org/bitbake/commit/?id=66306d5151acb0a26a171c338d8f60eb9eb16c6b

qmake5: Move to EXPORT_FUNCTIONS

---

recipes-qt/qt5/qtbase/0001-CVE-2023-51714-qtbase-5.15.diff
recipes-qt/qt5/qtbase/0002-CVE-2023-51714-qtbase-5.15.diff
recipes-qt/qt5/qtbase_git.bb

An issue was discovered in the HTTP2 implementation in Qt before 5.15.17, 6.x before 6.2.11, 6.3.x through 6.5.x before 6.5.4, and 6.6.x before 6.6.2. network/access/http2/hpacktable.cpp has an incorrect HPack integer overflow check.
Advisory:
- https://nvd.nist.gov/vuln/detail/CVE-2023-51714
Patch:
- https://download.qt.io/official_releases/qt/5.15/0001-CVE-2023-51714-qtbase-5.15.diff
- https://download.qt.io/official_releases/qt/5.15/0002-CVE-2023-51714-qtbase-5.15.diff

qtbase: Pick CVE-2023-51714 fix

---

recipes-python/pyqt5/python3-pyqt-builder-native_1.16.0.bb

OE dunfell builds have to inherit setuptools3, while anything newer has to inherit python_setuptools_build_meta. While OE dunfell is now EOL, this layer still claims to support it, so make it buildable and avoid breakage until the layer stops to support OE dunfell for good. Once that happens, this commit should be reverted.

python3-pyqt-builder-native: Fix OE dunfell build

---

recipes-qt/qt5/qtbase/CVE-2024-25580.patch
recipes-qt/qt5/qtbase_git.bb

CVE fixed:
-CVE-2024-25580: qtbase: potential buffer overflow when reading KTX images Upstream-Status: Backport from https://download.qt.io/official_releases/qt/5.15/CVE-2024-25580-qtbase-5.15.diff

qtbase: Security fix for CVE-2024-25580

---

classes/qmake5_base.bbclass
recipes-python/pyqt5/python3-pyqt5_5.15.10.bb
recipes-qt/qt5/ptest/run-ptest
recipes-qt/qt5/qt5-ptest.inc
recipes-qt/qt5/qtdeclarative_git.bb

- do not use `${}` in nested shell functions to mix bitbake's shell variables
- git rid of `local` which is not a POSIX variant
Signed-off-by: Valek Andrej <andrej.v@skyrain.eu>

qt5: do not mix bitbake's shell variables

---

compat/legacy/recipes-qt/packagegroups/nativesdk-packagegroup-qt5-toolchain-host.bbappend
compat/scarthgap/recipes-qt/packagegroups/nativesdk-packagegroup-qt5-toolchain-host.bbappend
conf/layer.conf
recipes-python/pyqt5/python3-pyqt-builder-native_1.16.0.bb
recipes-qt/demo-extrafiles/qt5-demo-extrafiles.bb
recipes-qt/maliit/maliit-framework-qt5_git.bb
recipes-qt/packagegroups/nativesdk-packagegroup-qt5-toolchain-host.bb
recipes-qt/qt-kiosk-browser/qt-kiosk-browser_git.bb
recipes-qt/qt5/nativesdk-qtbase_git.bb

refs:  https://lists.openembedded.org/g/openembedded-architecture/message/2007
fixes:
ERROR: /tmp/test/meta-qt5/recipes-qt/demo-extrafiles/qt5-demo-extrafiles.bb: Using S = ${WORKDIR} is no longer supported
and
install: cannot stat 'build/tmp/work/all-poky-linux/qt5-demo-extrafiles/1.0/cinematicexperience.png': No such file or directory
...

use UNPACKDIR

---

recipes-qt/qt5/qtbase_git.bb

The current code assumes 'examples' is always part of PACKAGECONFIG, causing do_install errors during the build. This commit adds checks to verify whether 'examples' is in PACKAGECONFIG before attempting to process them.
Fixes: 6fe2990d3580 ("qtbase: Remove references to buildmachine paths")
Fixes: 6bf5c6b6e3b3 ("qtbase: Remove the build path from the header of generated files")
Closes: #596

qtbase: Fix build errors when 'examples' is not in PACKAGECONFIG

---

recipes-qt/qt5/qtbase_git.bb

Fix the "contains reference to TMPDIR [buildpaths]" in source code of tests
Similar to issue:
6bf5c6b6e3 qtbase: Remove the build path from the header of generated files

qtbase: Remove the build path from the header of generated files in tests

---

conf/layer.conf

OE-core master dropped styhead from LAYERSERIES_CORENAMES.

layer.conf: Update for the walnascar release series

---

recipes-qt/qt5/qtbase_git.bb
recipes-qt/qt5/qtdeclarative_git.bb

Commit "qtbase: Remove references to buildmachine paths" (6fe2990d) and a few other related commits need to consider the case where QT_DIR_NAME is set.
Fix these paths to use the OE_QMAKE_PATH_* variables that contain the QT_DIR_NAME.

qtbase: update buildmachine fixup paths to honor QT_DIR_NAME

---

recipes-qt/qt5/qtdeclarative_git.bb
recipes-qt/qt5/qtxmlpatterns_git.bb

Skip the QA tests on failing modules until tests can be fixed.
Recently, I have been very troubled by this issue. Seeing that Qt6 handles it this way, temporarily adopted the same approach in Qt5 as well.
https://code.qt.io/cgit/yocto/meta-qt6.git/commit/recipes-qt/qt6/qtdeclarative_git.bb?id=39560e55667b6e8e2f971d040697f084eb936b1d

ptest: skip buildpaths QA tests for ptest packages

---

recipes-qt/qt5/qtwebengine_git.bb

This PR aims to solve https://github.com/meta-qt5/meta-qt5/issues/609

qtwebengine: disable linker GCS warning on aarch64
